import { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
const formatDate = value => value ? new Intl.RelativeTimeFormat('en', { numeric: 'auto' }).format(Math.round((new Date(value) - new Date()) / 86400000), 'day') : '—';
const salary = job => job.salary_min ? `₹${(job.salary_min / 100000).toFixed(1)}L – ₹${(job.salary_max / 100000).toFixed(1)}L` : 'Not disclosed';

function App() {
  const [jobs, setJobs] = useState([]); const [sources, setSources] = useState([]); const [analytics, setAnalytics] = useState(null);
  const [search, setSearch] = useState(''); const [source, setSource] = useState('All'); const [view, setView] = useState('table'); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); const params = new URLSearchParams({ search, source, per_page: 50 }); const [jobData, sourceData, analyticsData] = await Promise.all([fetch(`${API}/jobs?${params}`).then(r => r.json()), fetch(`${API}/sources`).then(r => r.json()), fetch(`${API}/analytics`).then(r => r.json())]); setJobs(jobData.items); setSources(sourceData); setAnalytics(analyticsData); setLoading(false); };
  useEffect(() => { load(); }, [source]);
  const sourceOptions = useMemo(() => ['All', ...sources.map(s => s.name)], [sources]);
  const toggle = async (id, action) => { await fetch(`${API}/jobs/${id}/${action}`, { method: 'POST' }); load(); };
  const refreshLive = async () => { setLoading(true); const roles = search.trim() ? [search] : []; const response = await fetch(`${API}/sources/remotive/refresh`, { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({roles}) }); if (!response.ok) { alert('Live jobs could not be loaded. Check the Flask terminal and your internet connection.'); } await load(); };
  return <div className="shell"><aside><div className="brand"><span>✦</span> RoleRadar</div><p className="workspace">PERSONAL JOB SEARCH</p>{['Dashboard', 'Jobs', 'Saved jobs', 'Applications', 'Resume', 'Job alerts', 'Analytics', 'Sources', 'Settings'].map((item, i) => <button className={i === 1 ? 'nav active' : 'nav'} key={item}>{['◫','⌕','♡','◷','▱','◉','◔','◌','⚙'][i]} {item}</button>)}<div className="aside-note"><b>Compliant sources only</b><br/>Use public APIs, feeds, or permitted company career pages.</div></aside><main><header><div><p className="eyebrow">JOB DISCOVERY</p><h1>Your job market, in one place.</h1></div><button className="profile">SC <span>⌄</span></button></header><section className="search-panel"><div className="search"><span>⌕</span><input value={search} onChange={e => setSearch(e.target.value)} onKeyDown={e => e.key === 'Enter' && load()} placeholder="Search roles, companies, or skills"/><button onClick={load}>Search</button></div><div className="filter-row"><span>Source</span>{sourceOptions.map(item => <button key={item} onClick={() => setSource(item)} className={source === item ? 'chip selected' : 'chip'}>{item}</button>)}<span className="divider"/><button className="filter" onClick={refreshLive}>↻ Fetch live remote jobs</button></div></section><section className="stats">{[{label:'Total jobs', value:analytics?.total_jobs ?? '—', hint:'across enabled sources'}, {label:'High match', value:analytics?.high_match ?? '—', hint:'80% match or above'}, {label:'Saved', value:analytics?.saved ?? '—', hint:'in your shortlist'}].map(stat => <article key={stat.label}><p>{stat.label}</p><strong>{stat.value}</strong><small>{stat.hint}</small></article>)}</section><section className="content-head"><div><h2>Recommended jobs <span>{jobs.length}</span></h2><p>Ranked by how closely they fit your profile.</p></div><div className="view-switch"><button onClick={() => setView('table')} className={view === 'table' ? 'selected' : ''}>☷ Table</button><button onClick={() => setView('cards')} className={view === 'cards' ? 'selected' : ''}>▦ Cards</button></div></section>{loading ? <div className="empty">Loading jobs…</div> : view === 'table' ? <JobTable jobs={jobs} toggle={toggle}/> : <JobCards jobs={jobs} toggle={toggle}/>}</main></div>
}
function Tags({items}) { return <div className="tags">{items.slice(0, 3).map(tag => <span key={tag}>{tag}</span>)}{items.length > 3 && <span>+{items.length - 3}</span>}</div> }
function Match({score}) { return <span className={'match ' + (score >= 85 ? 'great' : '')}>{score}%</span> }
function ApplyLink({job, label = 'Apply ↗'}) { return job.source === 'Demo Public Feed' ? <span className="demo-link">Demo only</span> : <a href={job.application_url} target="_blank" rel="noreferrer">{label}</a> }
function JobTable({jobs, toggle}) { return <div className="table-wrap"><table><thead><tr><th>Role</th><th>Location</th><th>Experience</th><th>Skills</th><th>Source</th><th>Match</th><th>Posted</th><th></th></tr></thead><tbody>{jobs.map(job => <tr key={job.id}><td><b>{job.job_title}</b><small>{job.company_name}</small></td><td>{job.location}<small>{job.remote_type}</small></td><td>{job.experience_min ?? 0}–{job.experience_max ?? '—'} yrs</td><td><Tags items={job.technologies}/></td><td><span className="source">{job.source}</span></td><td><Match score={job.match_score}/></td><td>{formatDate(job.posted_date)}</td><td className="actions"><button onClick={() => toggle(job.id, 'save')}>{job.is_saved ? '♥' : '♡'}</button><ApplyLink job={job}/></td></tr>)}</tbody></table>{!jobs.length && <div className="empty">No jobs match those filters.</div>}</div> }
function JobCards({jobs, toggle}) { return <div className="cards">{jobs.map(job => <article className="card" key={job.id}><div className="card-top"><div><span className="source">{job.source}</span><h3>{job.job_title}</h3><p>{job.company_name} · {job.location}</p></div><Match score={job.match_score}/></div><p className="description">{job.job_description}</p><Tags items={job.technologies}/><div className="meta"><span>💼 {job.employment_type}</span><span>⌛ {job.experience_min}–{job.experience_max} yrs</span><span>₹ {salary(job)}</span></div><footer><button onClick={() => toggle(job.id, 'save')}>{job.is_saved ? 'Saved ♥' : 'Save ♡'}</button><ApplyLink job={job} label="View & apply ↗"/></footer></article>)}</div> }
createRoot(document.getElementById('root')).render(<App/>);
